service: hello

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-sls-hello
  apiGateway:
    restApiId: ${ssm:/terraform/${self:provider.stage}/api_gateway/id}
    restApiRootResourceId: ${ssm:/terraform/${self:provider.stage}/api_gateway/root_resource_id}
  ecr:
    images:
      default:
        path: ./
        file: Dockerfile
        buildArgs:

functions:
  hello:
    name: ${self:provider.stage}-hello
    image:
      name: default
      command:
        - handler.hello
    events:
      - http:
          path: /hello
          method: GET
          authorizer:
            type: request
            identitySource: method.request.header.Cookie
            resultTtlInSeconds: 0
            name: ${self:provider.stage}-authorizer
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:provider.stage}-authorizer

plugins:
  - serverless-deployment-bucket
