service: checklist

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-sls-checklist
  iam:
    role: ${ssm:/terraform/shared/iam/lambda_role_arn}
  apiGateway:
    restApiId: ${ssm:/terraform/${self:provider.stage}/api_gateway/id}
    restApiRootResourceId: ${ssm:/terraform/${self:provider.stage}/api_gateway/root_resource_id}
  ecr:
    images:
      default:
        path: ./
        file: Dockerfile
        buildArgs:
  environment:
    ENVIRONMENT: ${self:provider.stage}
    OPENAI_API_KEY: ${ssm:/secrets/${self:provider.stage}/openai_api_key}
    GITHUB_TOKEN: ${ssm:/secrets/${self:provider.stage}/github_token}
    GITHUB_FERNET_KEY: ${ssm:/secrets/${self:provider.stage}/github_fernet_key}
    POSTGRES_HOST: ${ssm:/terraform/${self:provider.stage}/rds/endpoint}
    POSTGRES_PORT: ${ssm:/terraform/${self:provider.stage}/rds/port}
    POSTGRES_DB: ${ssm:/terraform/${self:provider.stage}/rds/db_name}
    POSTGRES_USER: ${ssm:/terraform/${self:provider.stage}/rds/db_username}
    POSTGRES_PASSWORD: ${ssm:/terraform/${self:provider.stage}/rds/db_password}
    CHECKLIST_EVALUATION_PROCESSOR_QUEUE_URL: ${ssm:/terraform/${self:provider.stage}/sqs/checklist_evaluation_processor_queue_url}
    CHECKLIST_GENERATION_PROCESSOR_QUEUE_URL: ${ssm:/terraform/${self:provider.stage}/sqs/checklist_generation_processor_queue_url}
    QUESTION_GENERATION_PROCESSOR_QUEUE_URL: ${ssm:/terraform/${self:provider.stage}/sqs/question_generation_processor_queue_url}

functions:
  evaluation-processor:
    name: ${self:provider.stage}-checklist-evaluation-processor
    image:
      name: default
      command:
        - evaluate.handler
    events:
      - sqs: ${ssm:/terraform/${self:provider.stage}/sqs/checklist_evaluation_processor_queue_arn}
    timeout: 300

  generation-processor:
    name: ${self:provider.stage}-checklist-generation-processor
    image:
      name: default
      command:
        - generate.handler
    events:
      - sqs: ${ssm:/terraform/${self:provider.stage}/sqs/checklist_generation_processor_queue_arn}
    timeout: 300

  retrieve:
    name: ${self:provider.stage}-checklist-retrieve
    image:
      name: default
      command:
        - retrieve.handler
    events:
      - http:
          path: /checklists/{id}
          method: GET
          cors:
            origins:
              - https://www.matchyaa.com
              - https://matchyaa.com
              - http://127.0.0.1:5173
            allowCredentials: true
          authorizer:
            type: request
            identitySource: method.request.header.Cookie
            resultTtlInSeconds: 300
            name: ${self:provider.stage}-checklist-retrieve-authorizer
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:provider.stage}-authorizer
          request:
            parameters:
              paths:
                id: true

  evaluation-publisher:
    name: ${self:provider.stage}-checklist-evaluation-publisher
    image:
      name: default
      command:
        - publish_evaluation.handler
    events:
      - http:
          path: /checklists/evaluate
          method: POST
          cors:
            origins:
              - https://www.matchyaa.com
              - https://matchyaa.com
              - http://127.0.0.1:5173
            allowCredentials: true
          authorizer:
            type: request
            identitySource: method.request.header.Cookie
            resultTtlInSeconds: 300
            name: ${self:provider.stage}-checklist-evaluation-publisher-authorizer
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:provider.stage}-authorizer
    timeout: 30

  generation-publisher:
    name: ${self:provider.stage}-checklist-generation-publisher
    image:
      name: default
      command:
        - publish_generation.handler
    events:
      - http:
          path: /checklists/generate
          method: POST
          cors:
            origins:
              - https://www.matchyaa.com
              - https://matchyaa.com
              - http://127.0.0.1:5173
            allowCredentials: true
          authorizer:
            type: request
            identitySource: method.request.header.Cookie
            resultTtlInSeconds: 300
            name: ${self:provider.stage}-checklist-generation-publisher-authorizer
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:provider.stage}-authorizer
    timeout: 30

plugins:
  - serverless-deployment-bucket
