service: position

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-sls-position
  iam:
    role: ${ssm:/terraform/shared/iam/lambda_role_arn}
  apiGateway:
    restApiId: ${ssm:/terraform/${self:provider.stage}/api_gateway/id}
    restApiRootResourceId: ${ssm:/terraform/${self:provider.stage}/api_gateway/root_resource_id}
  ecr:
    images:
      default:
        path: ./
        file: Dockerfile
        buildArgs:
  environment:
    ENVIRONMENT: ${self:provider.stage}
    POSTGRES_HOST: ${ssm:/terraform/${self:provider.stage}/rds/endpoint}
    POSTGRES_PORT: ${ssm:/terraform/${self:provider.stage}/rds/port}
    POSTGRES_DB: ${ssm:/terraform/${self:provider.stage}/rds/db_name}
    POSTGRES_USER: ${ssm:/terraform/${self:provider.stage}/rds/db_username}
    POSTGRES_PASSWORD: ${ssm:/terraform/${self:provider.stage}/rds/db_password}

functions:
  retrieve:
    name: ${self:provider.stage}-position-retrieve
    image:
      name: default
      command:
        - retrieve.handler
    events:
      - http:
          path: /positions/{id}
          method: GET
          cors:
            origins:
              - https://www.matchyaa.com
              - https://matchyaa.com
              - http://127.0.0.1:5173
            allowCredentials: true
          authorizer:
            type: request
            identitySource: method.request.header.Cookie
            resultTtlInSeconds: 300
            name: ${self:provider.stage}-position-retrieve-authorizer
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:provider.stage}-authorizer
          request:
            parameters:
              paths:
                id: true
    timeout: 30

  create:
    name: ${self:provider.stage}-position-create
    image:
      name: default
      command:
        - create.handler
    events:
      - http:
          path: /positions
          method: POST
          cors:
            origins:
              - https://www.matchyaa.com
              - https://matchyaa.com
              - http://127.0.0.1:5173
            allowCredentials: true
          authorizer:
            type: request
            identitySource: method.request.header.Cookie
            resultTtlInSeconds: 300
            name: ${self:provider.stage}-position-create-authorizer
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:provider.stage}-authorizer

  checklist-status:
    name: ${self:provider.stage}-position-checklist-status
    image:
      name: default
      command:
        - checklist_status.handler
    events:
      - http:
          path: /positions/status/checklist/{id}
          method: GET
          cors:
            origins:
              - https://www.matchyaa.com
              - https://matchyaa.com
              - http://127.0.0.1:5173
            allowCredentials: true
          authorizer:
            type: request
            identitySource: method.request.header.Cookie
            resultTtlInSeconds: 300
            name: ${self:provider.stage}-position-checklist-status-authorizer
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:provider.stage}-authorizer
          request:
            parameters:
              paths:
                id: true

  retrieve-candidates:
    name: ${self:provider.stage}-position-retreive-candidates
    image:
      name: default
      command:
        - candidates.handler
    events:
      - http:
          path: /positions/candidates/{id}
          method: GET
          cors:
            origins:
              - https://www.matchyaa.com
              - https://matchyaa.com
              - http://127.0.0.1:5173
            allowCredentials: true
          authorizer:
            type: request
            identitySource: method.request.header.Cookie
            resultTtlInSeconds: 300
            name: ${self:provider.stage}-position-candidates-status-authorizer
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:provider.stage}-authorizer
          request:
            parameters:
              paths:
                id: true

  retrieve-questions:
    name: ${self:provider.stage}-position-retrieve-questions
    image:
      name: default
      command:
        - questions.handler
    events:
      - http:
          path: /positions/questions/{id}
          method: GET
          cors:
            origins:
              - https://www.matchyaa.com
              - https://matchyaa.com
              - https://www.staging.matchyaa.com
              - https://staging.matchyaa.com
              - http://127.0.0.1:5173
            allowCredentials: true
          authorizer:
            type: request
            identitySource: method.request.header.Cookie
            resultTtlInSeconds: 300
            name: ${self:provider.stage}-position-retrieve-questions-authorizer
            arn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:provider.stage}-authorizer
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-deployment-bucket
