service: registrar

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  stage: dev
  deploymentBucket:
    name: ${self:provider.stage}-sls-registrar

functions:
  register:
    handler: handler.register
    events:
      - http:
          path: /
          method: POST

plugins:
  - serverless-python-requirements
  - serverless-deployment-bucket
