service: registrar

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  stage: dev
  deploymentBucket:
    name: ${self:provider.stage}-sls-registrar

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: GET

plugins:
  - serverless-python-requirements
  - serverless-deployment-bucket
