service: criteria

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-sls-criteria
  iam:
    role: ${ssm:/terraform/iam/lambda-role-arn}
  apiGateway:
    restApiId: ${ssm:/terraform/api_gateway/id}
    restApiRootResourceId: ${ssm:/terraform/api_gateway/root_resource_id}
  ecr:
    images:
      default:
        path: ./
        file: Dockerfile
        buildArgs:

  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}

functions:
  evaluate:
    name: ${self:provider.stage}-criteria-evaluate
    timeout: 60
    image:
      name: default
      command:
        - evaluate.handler
    events:
      - http:
          path: /evaluate
          method: POST

  generate:
    name: ${self:provider.stage}-criteria-generate
    image:
      name: default
      command:
        - generate.handler
    events:
      - http:
          path: /generate
          method: POST

  retrieve:
    name: ${self:provider.stage}-criteria-retrieve
    image:
      name: default
      command:
        - retrieve.handler
    events:
      - http:
          path: /criteria/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-deployment-bucket
