service: video

frameworkVersion: "3"

custom: ${file(../shared/serverless.yml):custom}

provider: ${file(../shared/serverless.yml):provider}

functions:
  get-presigned-url:
    name: ${self:provider.stage}-${self:service}-get-presigned-url
    image:
      name: default
      command:
        - get_presigned_url.handler
    events:
      - http:
          path: /videos/presigned-url
          method: GET
          cors: ${file(../shared/serverless.yml):cors}
    timeout: 30

plugins:
  - serverless-deployment-bucket
