service: question

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-sls-question
  iam:
    role: ${ssm:/terraform/shared/iam/lambda_role_arn}
  apiGateway:
    restApiId: ${ssm:/terraform/${self:provider.stage}/api_gateway/id}
    restApiRootResourceId: ${ssm:/terraform/${self:provider.stage}/api_gateway/root_resource_id}
  ecr:
    images:
      default:
        path: ./
        file: Dockerfile
        buildArgs:
  environment:
    ENVIRONMENT: ${self:provider.stage}
    OPENAI_API_KEY: ${ssm:/secrets/${self:provider.stage}/openai_api_key}
    POSTGRES_HOST: ${ssm:/terraform/${self:provider.stage}/rds/endpoint}
    POSTGRES_PORT: ${ssm:/terraform/${self:provider.stage}/rds/port}
    POSTGRES_DB: ${ssm:/terraform/${self:provider.stage}/rds/db_name}
    POSTGRES_USER: ${ssm:/terraform/${self:provider.stage}/rds/db_username}
    POSTGRES_PASSWORD: ${ssm:/terraform/${self:provider.stage}/rds/db_password}
    QUESTION_GENERATION_PROCESSOR_QUEUE_URL: ${ssm:/terraform/${self:provider.stage}/sqs/question_generation_processor_queue_url}

functions:
  evaluate:
    name: ${self:provider.stage}-question-evaluate
    image:
      name: default
      command:
        - evaluate.handler
    events:
      - s3:
          bucket: ${self:provider.stage}-data-candidate-response
          event: s3:ObjectCreated:*
          existing: true
    timeout: 300

plugins:
  - serverless-deployment-bucket
