service: candidate

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-sls-candidate
  iam:
    role: ${ssm:/terraform/shared/iam/lambda_role_arn}
  apiGateway:
    restApiId: ${ssm:/terraform/${self:provider.stage}/api_gateway/id}
    restApiRootResourceId: ${ssm:/terraform/${self:provider.stage}/api_gateway/root_resource_id}
  ecr:
    images:
      default:
        path: ./
        file: Dockerfile
        buildArgs:
  environment:
    ENVIRONMENT: ${self:provider.stage}
    OPENAI_API_KEY: ${ssm:/secrets/${self:provider.stage}/openai_api_key}
    POSTGRES_HOST: ${ssm:/terraform/${self:provider.stage}/rds/endpoint}
    POSTGRES_PORT: ${ssm:/terraform/${self:provider.stage}/rds/port}
    POSTGRES_DB: ${ssm:/terraform/${self:provider.stage}/rds/db_name}
    POSTGRES_USER: ${ssm:/terraform/${self:provider.stage}/rds/db_username}
    POSTGRES_PASSWORD: ${ssm:/terraform/${self:provider.stage}/rds/db_password}

custom:
  origins:
    staging:
      - "https://${ssm:/terraform/staging/domain_name}"
      - "https://www.${ssm:/terraform/staging/domain_name}"
    dev:
      - "http://127.0.0.1:5173"

functions:
  add:
    name: ${self:provider.stage}-candidate-add
    image:
      name: default
      command:
        - add.handler
    events:
      - http:
          path: /candidates
          method: POST
          cors:
            origins: ${self:custom.origins.${self:provider.stage}}
            allowCredentials: true
          authorizer:
            authorizerId: ${cf:authorizer-${self:provider.stage}.AuthorizerId}
            type: REQUEST
    timeout: 30

  retrieve:
    name: ${self:provider.stage}-candidate-retrieve
    image:
      name: default
      command:
        - retrieve.handler
    events:
      - http:
          path: /candidates
          method: GET
          cors:
            origins: ${self:custom.origins.${self:provider.stage}}
            allowCredentials: true
          authorizer:
            authorizerId: ${cf:authorizer-${self:provider.stage}.AuthorizerId}
            type: REQUEST
    timeout: 30

  retrieve-result:
    name: ${self:provider.stage}-candidate-retrieve-result
    image:
      name: default
      command:
        - retrieve_result.handler
    events:
      - http:
          path: /candidates/result/{candidate_result_id}
          method: GET
          cors:
            origins: ${self:custom.origins.${self:provider.stage}}
            allowCredentials: true
          authorizer:
            authorizerId: ${cf:authorizer-${self:provider.stage}.AuthorizerId}
            type: REQUEST
          request:
            parameters:
              paths:
                candidate_result_id: true
    timeout: 30

  evaluate:
    name: ${self:provider.stage}-candidate-evaluate
    image:
      name: default
      command:
        - evaluate.handler
    events:
      - http:
          path: /candidates/evaluate
          method: POST
          cors:
            origins: ${self:custom.origins.${self:provider.stage}}
            allowCredentials: true
          authorizer:
            authorizerId: ${cf:authorizer-${self:provider.stage}.AuthorizerId}
            type: REQUEST
    timeout: 30

plugins:
  - serverless-deployment-bucket
