service: generator
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: dev
  ecr:
    images:
      generator_lambda:
        path: ./
        file: Dockerfile
        buildArgs:
  architecture: arm64
  iam:
    role: ${ssm:/terraform/iam/lambda-role-arn}
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    ENVIRONMENT: ${env:ENVIRONMENT}

functions:
  generate_criteria:
    image:
      name: generator_lambda
      command:
        - handler.generate_criteria

    events:
      - http:
          path: /generate
          method: POST

custom:
  export-env:
    filename: .env
    overwrite: true
