service: assessment

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-sls-assessment
  iam:
    role: ${ssm:/terraform/shared/iam/lambda_role_arn}
  apiGateway:
    restApiId: ${ssm:/terraform/${self:provider.stage}/api_gateway/id}
    restApiRootResourceId: ${ssm:/terraform/${self:provider.stage}/api_gateway/root_resource_id}
  ecr:
    images:
      default:
        path: ./
        file: Dockerfile
        buildArgs:
  environment:
    ENVIRONMENT: ${self:provider.stage}
    POSTGRES_HOST: ${ssm:/terraform/${self:provider.stage}/rds/endpoint}
    POSTGRES_PORT: ${ssm:/terraform/${self:provider.stage}/rds/port}
    POSTGRES_DB: ${ssm:/terraform/${self:provider.stage}/rds/db_name}
    POSTGRES_USER: ${ssm:/terraform/${self:provider.stage}/rds/db_username}
    POSTGRES_PASSWORD: ${ssm:/terraform/${self:provider.stage}/rds/db_password}
    QUESTION_GENERATION_PROCESSOR_QUEUE_URL: ${ssm:/terraform/${self:provider.stage}/sqs/question_generation_processor_queue_url}

custom:
  origins:
    staging:
      - "https://${ssm:/terraform/staging/domain_name}"
      - "https://www.${ssm:/terraform/staging/domain_name}"
    dev:
      - "http://127.0.0.1:5173"

functions:
  create:
    name: ${self:provider.stage}-assessment-create
    image:
      name: default
      command:
        - create.handler
    events:
      - http:
          path: /assessments
          method: POST
          cors:
            origins: ${self:custom.origins.${self:provider.stage}}
            allowCredentials: true
          authorizer:
            authorizerId: ${cf:authorizer-${self:provider.stage}.AuthorizerId}
            type: REQUEST

  retrieve:
    name: ${self:provider.stage}-assessment-retrieve
    image:
      name: default
      command:
        - retrieve.handler
    events:
      - http:
          path: /assessments
          method: GET
          cors:
            origins: ${self:custom.origins.${self:provider.stage}}
            allowCredentials: true
          authorizer:
            authorizerId: ${cf:authorizer-${self:provider.stage}.AuthorizerId}
            type: REQUEST

  retrieve-by-id:
    name: ${self:provider.stage}-assessment-retrieve-by-id
    image:
      name: default
      command:
        - retrieve_by_id.handler
    events:
      - http:
          path: /assessments/{id}
          method: GET
          cors:
            origins: ${self:custom.origins.${self:provider.stage}}
            allowCredentials: true
          authorizer:
            authorizerId: ${cf:authorizer-${self:provider.stage}.AuthorizerId}
            type: REQUEST
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-deployment-bucket
