service: company

frameworkVersion: "3"

custom: ${file(../shared/serverless.yml):custom}

provider: ${file(../shared/serverless.yml):provider}

functions:
  me:
    name: ${self:provider.stage}-company-me
    image:
      name: default
      command:
        - me.handler
    events:
      - http:
          path: /companies/me
          method: GET
          cors: ${file(../shared/serverless.yml):cors}
          authorizer: ${file(../shared/serverless.yml):cookie-authorizer}

plugins:
  - serverless-deployment-bucket
