service: authentication

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-sls-authentication
  iam:
    role: ${ssm:/terraform/iam/lambda-role-arn}
  apiGateway:
    restApiId: ${ssm:/terraform/api_gateway/id}
    restApiRootResourceId: ${ssm:/terraform/api_gateway/root_resource_id}
  ecr:
    images:
      default:
        path: ./
        file: Dockerfile
        buildArgs:

functions:
  register:
    name: ${self:provider.stage}-authentication-register
    image:
      name: default
      command:
        - handler.register
    environment:
      ENVIRONMENT: ${self:provider.stage}
    events:
      - http:
          path: /register
          method: POST
  login:
    name: ${self:provider.stage}-authentication-login
    image:
      name: default
      command:
        - handler.login
    environment:
      ENVIRONMENT: ${self:provider.stage}
    events:
      - http:
          path: /login
          method: POST

plugins:
  - serverless-deployment-bucket
