service: authentication

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-sls-authentication
  iam:
    role: ${ssm:/terraform/shared/iam/lambda_role_arn}
  apiGateway:
    restApiId: ${ssm:/terraform/${self:provider.stage}/api_gateway/id}
    restApiRootResourceId: ${ssm:/terraform/${self:provider.stage}/api_gateway/root_resource_id}
  ecr:
    images:
      default:
        path: ./
        file: Dockerfile
        buildArgs:
  environment:
    ENVIRONMENT: ${self:provider.stage}
    JWT_SECRET_KEY: ${ssm:/secrets/${self:provider.stage}/jwt_secret_key}
    POSTGRES_HOST: ${ssm:/terraform/${self:provider.stage}/rds/endpoint}
    POSTGRES_PORT: ${ssm:/terraform/${self:provider.stage}/rds/port}
    POSTGRES_DB: ${ssm:/terraform/${self:provider.stage}/rds/db_name}
    POSTGRES_USER: ${ssm:/terraform/${self:provider.stage}/rds/db_username}
    POSTGRES_PASSWORD: ${ssm:/terraform/${self:provider.stage}/rds/db_password}

functions:
  register:
    name: ${self:provider.stage}-authentication-register
    image:
      name: default
      command:
        - register.handler
    environment:
      ENVIRONMENT: ${self:provider.stage}
    events:
      - http:
          path: /register
          method: POST
          cors: true

  login:
    name: ${self:provider.stage}-authentication-login
    image:
      name: default
      command:
        - login.handler
    environment:
      ENVIRONMENT: ${self:provider.stage}
    events:
      - http:
          path: /login
          method: POST
          cors: true

plugins:
  - serverless-deployment-bucket
