service: authentication

frameworkVersion: "3"

custom: ${file(../shared/serverless.yml):custom}

provider: ${file(../shared/serverless.yml):provider}

functions:
  logout:
    name: ${self:provider.stage}-authentication-logout
    image:
      name: default
      command:
        - logout.handler
    events:
      - http:
          path: /logout
          method: POST
          cors: ${file(../shared/serverless.yml):cors}

  google:
    name: ${self:provider.stage}-authentication-google
    image:
      name: default
      command:
        - google.handler
    events:
      - http:
          path: /login/google
          method: POST
          cors: ${file(../shared/serverless.yml):cors}

  invitation:
    name: ${self:provider.stage}-authentication-invitation
    image:
      name: default
      command:
        - invitation.handler
    events:
      - http:
          path: /auth/invitation
          method: POST
          cors: ${file(../shared/serverless.yml):cors}

  invitation-invalidate:
    name: ${self:provider.stage}-authentication-invitation-invalidate
    image:
      name: default
      command:
        - invitation_invalidate.handler
    events:
      - http:
          path: /auth/invitation/invalidate
          method: POST
          cors: ${file(../shared/serverless.yml):cors}
          authorizer: ${file(../shared/serverless.yml):header-authorizer}

plugins:
  - serverless-deployment-bucket
