on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"

jobs:
  s3:
    name: Deploy to S3
    uses: ./.github/workflows/job-deploy-to-s3.yml
    with:
      environment: ${{inputs.environment}}
