name: Manually Deploy DB Changelog

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to in lowercase."
        required: true
        default: "staging"
      environment-label:
        description: "Environment to deploy to in capitalized."
        required: true
        default: "Staging"

jobs:
  deploy-db-changelog:
    name: Deployment
    uses: ./.github/workflows/job-deploy-db-changelog.yml
    with:
      environment: ${{ inputs.environment }}
      environment-label: ${{ inputs.environment-label }}
    secrets: inherit
