name: Manually Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      label:
        description: "Label for the deployment"
        required: true
        default: "Shared"
      component:
        description: "Component to deploy"
        required: true
        type: string
        default: "shared"
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"

jobs:
  shared:
    name: Deployment
    uses: ./.github/workflows/job-deploy-terraform.yml
    with:
      environment: ${{inputs.environment}}
      component: ${{inputs.component}}
      label: ${{inputs.label}}
    secrets: inherit

  environment:
    name: Deployment
    needs: [shared]
    uses: ./.github/workflows/job-deploy-terraform.yml
    with:
      environment: ${{inputs.environment}}
      component: ${{inputs.component}}
      label: ${{inputs.label}}
    secrets: inherit
