on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
      environment-label:
        description: "Label for the environment"
        required: true
        type: string
      component:
        description: "Component to deploy"
        required: true
        type: string
      label:
        description: "Label for the job"
        required: true
        type: string

jobs:
  run:
    name: ${{ inputs.label }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-label }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup SSH Key (Shared)
        if: inputs.component == 'shared'
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa_matchya.pub
          chmod 600 ~/.ssh/id_rsa_matchya.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/${{ inputs.component }}

      - name: Select Workspace (Environment)
        if: inputs.component == 'environment'
        run: |
          terraform workspace select ${{ inputs.environment }}
        working-directory: terraform/${{ inputs.component }}

      - name: Set Terraform Variables (Environment)
        if: inputs.component == 'environment'
        run: |
          echo 'namespace = "${{ secrets.TF_NAMESPACE}}"' >> terraform.tfvars
          echo 'db_username = "${{ secrets.TF_DB_USERNAME }}"' >> terraform.tfvars
          echo 'db_password = "${{ secrets.TF_DB_PASSWORD}}"' >> terraform.tfvars
          echo 'client_origin = "${{ vars.TF_CLIENT_ORIGIN }}"' >> terraform.tfvars
        working-directory: terraform/${{ inputs.component }}

      - name: Set Terraform Variables (Shared)
        if: inputs.component == 'shared'
        run: |
          echo 'domain_name = {' > terraform.tfvars
          echo '  "prod": "${{ vars.TF_PRODUCTION_DOMAIN_NAME }}",' >> terraform.tfvars
          echo '  "staging": "${{ vars.TF_STAGING_DOMAIN_NAME }}"' >> terraform.tfvars
          echo '}' >> terraform.tfvars
        working-directory: terraform/${{ inputs.component }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=${{ inputs.component }}.tfplan -no-color | tee plan_output.txt
        working-directory: terraform/${{ inputs.component }}

      - name: Upload Terraform Plan to S3
        run: aws s3 cp terraform/${{ inputs.component }}/${{ inputs.component }}.tfplan s3://matchya-terraform/github-actions-artifacts/${{ inputs.environment }}/plans/${{ inputs.component }}.tfplan

      - name: Comment PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('terraform/${{ inputs.component }}/plan_output.txt', 'utf8');
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '```terraform\n' + output + '\n```'
            })
