on:
  workflow_call:
    inputs:
      label:
        description: "Name of the component to deploy"
        type: string
        required: true
      component:
        description: "Component to deploy"
        type: string
        required: true
      environment:
        description: "Environment to deploy"
        type: string
        required: true
        default: "staging"
    secrets:
      AWS_ACCESS_KEY_ID:
        description: "AWS Access Key ID"
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: "AWS Secret Access Key"
        required: true

jobs:
  run:
    name: ${{inputs.label}} Infrastructure
    runs-on: ubuntu-latest
    permissions: write-all
    environment: ${{inputs.environment}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Terraform Plan from S3
        run: aws s3 cp s3://github-actions-remote-artifacts/${{inputs.environment}}/plans/${{inputs.component}}.tfplan terraform/${{inputs.component}}/${{inputs.component}}.tfplan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/${{inputs.component}}

      - name: Select Terraform Workspace
        if: ${{inputs.component == 'environment'}}
        run: terraform workspace select ${{inputs.environment}}
        working-directory: terraform/${{inputs.component}}

      - name: Terraform Apply
        run: terraform apply -auto-approve ${{inputs.component}}.tfplan
        working-directory: terraform/${{inputs.component}}
