on:
  workflow_call:

jobs:
  run:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to S3
        shell: bash
        run: |
          bash scripts/deploy_to_s3.sh --bucket-name ${{ secrets.WEBSITE_BUCKET_NAME }} --environment ${{ github.event.inputs.environment }}
