on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: number
    outputs:
      should_prepare_web_release:
        description: "Indicates if a Web release should be prepared"
        value: ${{ jobs.run.outputs.should_prepare_web_release }}
      should_prepare_server_release:
        description: "Indicates if a Server release should be prepared"
        value: ${{ jobs.run.outputs.should_prepare_server_release }}

jobs:
  run:
    name: Commits
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ['web', 'server']
    outputs:
      should_prepare_web_release: ${{ steps.analyze.outputs.should_prepare_web_release }}
      should_prepare_server_release: ${{ steps.analyze.outputs.should_prepare_server_release }}
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
            ref: 'develop'
            fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Gather and comment PR with changes
        id: analyze
        run: |
          git fetch origin main
          git fetch origin develop
          changes=""
          if [ "${{ matrix.component }}" == "web" ]; then
            scopes=('web')
          elif [ "${{ matrix.component }}" == "server" ]; then
            scopes=('authentication' 'authorizer' 'checklist' 'company' 'position')
          fi
          for scope_item in "${scopes[@]}"; do
            scope_changes=$(git log --pretty=format:"%s" origin/main..origin/develop | grep -E "feat\($scope_item\)|fix\($scope_item\)|chore\($scope_item\)" || echo "")
            if [ "$scope_changes" == "" ]; then
              changes+="$scope_changes"$'\n'
            fi
          done
          if [ "$changes" == "" ]; then
            if [ "${{ matrix.component }}" == "web" ]; then
              echo "There were changes in web..."
              echo "true" > web_release_decision.txt
            elif [ "${{ matrix.component }}" == "server" ]; then
              echo "There were changes in server..."
              echo "true" > server_release_decision.txt
              echo "::set-output name=should_prepare_server_release::true"
            fi
            gh pr comment "$PULL_REQUEST_NUMBER" --body $'### 🚀 **Preparing for '"$COMPONENT"$' release**\nThese changes will be incorporated into the forthcoming release:\n\n'"$changes"$''
          else
            echo "No Changes..."
            echo "false" > web_release_decision.txt
            echo "false" > server_release_decision.txt
          fi
      - name: Upload release decision artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.component}}-release-decision
          path: ${{matrix.component}}-release_decision.txt
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COMPONENT: ${{ matrix.component }}
      PULL_REQUEST_NUMBER: ${{ inputs.pull_request_number }}
