on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment-label:
        required: true
        type: string

jobs:
  run:
    name: DB Changelog
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-label }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa_matchya.pub
          chmod 600 ~/.ssh/id_rsa_matchya.pub

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up SSH tunnel
        run: |
          make create-ssh-tunnel environment=${{ inputs.environment }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: db

      - name: Run Update Changelog
        run: |
          python ./update.py staging
        working-directory: db/scripts

      - name: Close SSH tunnel
        if: always()
        run: |
          make close-ssh-tunnel environment=${{ inputs.environment }}
