name: Merge Pipeline (Staging)

on:
  pull_request:
    branches:
      - staging
    types: [closed]

jobs:
  cleanup:
    if: github.event.pull_request.merged == true && github.head_ref == 'develop'
    name: Clean Deployment History
    runs-on: ubuntu-latest
    environment: staging
    env:
      ENVIRONMENT: staging
    permissions: write-all
    steps:
      - name: 🗑 Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          environment: ${{env.ENVIRONMENT}}
          token: ${{ secrets.GH_TOKEN }}
          onlyRemoveDeployments: true

  check-infrastructure-changes:
    if: github.event.pull_request.merged == true && github.head_ref == 'develop'
    name: Check Infrastructure Changes
    runs-on: ubuntu-latest
    outputs:
      infra-changed: ${{ steps.check.outputs.infra-changed }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Infrastructure Files Changed
        uses: dorny/paths-filter@v2
        id: changes-infrastructure
        with:
          filters: |
            package:
              - 'terraform/**'

      - name: Set output
        id: check
        run: echo "::set-output name=infra-changed::${{ steps.changes-infrastructure.outputs.package }}"

  deploy-terraform-shared:
    name: Deployment
    permissions: write-all
    needs: [check-infrastructure-changes]
    uses: ./.github/workflows/job-deploy-infrastructure.yml
    with:
      label: Shared Infrastructure
      component: shared
      environment: staging
    secrets: inherit

  deploy-terraform-environment:
    if: github.event.pull_request.merged == true && github.head_ref == 'develop'
    name: Deployment
    permissions: write-all
    needs: [deploy-terraform-shared]
    uses: ./.github/workflows/job-deploy-infrastructure.yml
    with:
      label: Environment Infrastructure
      component: environment
      environment: staging
    secrets: inherit

  deploy-website:
    if: github.event.pull_request.merged == true && github.head_ref == 'develop'
    name: Deployment
    needs: [cleanup]
    uses: ./.github/workflows/job-deploy-website.yml
    with:
      environment: staging
    secrets: inherit

  # create-release-web:
  #   name: Create Release (web)
  #   uses: ./.github/workflows/job-create-release.yml
  #   with:
  #     component: web
  #     environment: staging
  #   secrets: inherit

  # create-release-authentication:
  #   name: Create Release (authentication)
  #   needs: create-release-web
  #   uses: ./.github/workflows/job-create-release.yml
  #   with:
  #     component: authentication
  #     environment: staging
  #   secrets: inherit

  # create-release-authorizer:
  #   name: Create Release (authorizer)
  #   needs: create-release-authentication
  #   uses: ./.github/workflows/job-create-release.yml
  #   with:
  #     component: authorizer
  #     environment: staging
  #   secrets: inherit

  # create-release-checklist:
  #   name: Create Release (checklist)
  #   needs: create-release-authorizer
  #   uses: ./.github/workflows/job-create-release.yml
  #   with:
  #     component: checklist
  #     environment: staging
  #   secrets: inherit

  # create-release-company:
  #   name: Create Release (company)
  #   needs: create-release-checklist
  #   uses: ./.github/workflows/job-create-release.yml
  #   with:
  #     component: company
  #     environment: staging
  #   secrets: inherit

  # create-release-position:
  #   name: Create Release (position)
  #   needs: create-release-company
  #   uses: ./.github/workflows/job-create-release.yml
  #   with:
  #     component: position
  #     environment: staging
  #   secrets: inherit
