name: UI Pipeline

on:
  push:
    branches:
      - '385-featci-set-up-pipeline-to-deploy-to-s3'

jobs:
  deploy:
    name: Deploy UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Call Deploy UI
        uses: ./.github/workflows/call-deploy-ui.yml
      - name: Call Version Release
        uses: ./.github/workflows/call-version-release.yml
