name: UI Pipeline

on:
  push:

jobs:
  deploy:
    name: Deploy UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Call Deploy UI
        uses: ./.github/workflows/call-deploy-ui.yml
      - name: Call Version Release
        uses: ./.github/workflows/call-version-release.yml
