name: UI Pipeline

on:
  push:

jobs:
  deploy:
    name: Deploy UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Call Deploy to S3
        uses: ./.github/actions/call-deploy-to-s3/action.yml
      - name: Call Version Release
        uses: ./.github/actions/call-create-version-release/action.yml
