name: UI Release Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  analyze-commits:
    runs-on: ubuntu-latest
    outputs:
      should_prepare_release: ${{ steps.analyze.outputs.should_prepare_release }}
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: 'develop'
          fetch-depth: 0

      - name: Analyze commits
        id: analyze
        run: |
          if git log --pretty=format:"%s" -n 1 | grep -qE 'feat\(ui\)|fix\(ui\)|chore\(ui\)'; then
            echo "::set-output name=should_prepare_release::true"
          else
            echo "::set-output name=should_prepare_release::false"
          fi

  prepare-ui-release:
    needs: analyze-commits
    runs-on: ubuntu-latest
    if: ${{ needs.analyze-commits.outputs.should_prepare_release == 'true' }}
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: 'develop'
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create UI Release
        run: |
          echo "Creating UI Release..."
