name: Release UI

on:
  push:

jobs:
  release-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release-ui branch
        uses: actions/checkout@v2
        with:
          ref: release-ui

      - name: Pull main branch commits
        run: |
          git fetch origin main
          git merge origin/main

      - name: Cherry pick commits
        run: |
          git fetch origin develop
          git cherry-pick $(git log --grep='feat(ui)' --format="%H" origin/develop)
          git cherry-pick $(git log --grep='fix(ui)' --format="%H" origin/develop)
          git cherry-pick $(git log --grep='chore(ui)' --format="%H" origin/develop)

    # TODO: implement in the near future...
    #   - name: Run E2E tests
    #     run: npm run test:e2e

      - name: Wait for approval
        uses: actions/github-script@v3
        with:
          script: |
            const issue_number = context.issue.number;
            const result = await github.pulls.createReviewRequest({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: issue_number,
              reviewers: ['kokiebisu']
            });
            return result.data;

      - name: Semantic Release
        run: |
          cd web
          npm run release

      - name: Push to release-ui branch
        run: git push origin release-ui

      - name: Merge to main branch
        run: |
          git checkout main
          git merge --no-ff release-ui
          git push origin main
