name: Web Pipeline

on:
  push:

jobs:
  deploy-to-s3:
    name: Deploy to S3
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
    env:
      ENVIRONMENT: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set execute permissions for deploy script
        run: chmod +x scripts/deploy_to_s3.sh
      - name: Deploy to S3
        shell: bash
        run: |
          cd scripts && ./deploy_to_s3.sh --bucket-name ${{ secrets.WEBSITE_BUCKET_NAME }} --environment ${{ env.ENVIRONMENT }}


  create-version-release:
    name: Create Version Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - name: Install dependencies
        run: |
          cd web
          npm install
      - name: Build
        run: |
          cd web
          npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
