name: PR Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  validate:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Compare PR title with Regex
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PATTERN="^(feat|fix|perf|revert|styles|test|chore|refactor)(\(web\)|\(authentication\)|\(authorizer\)|\(assessment\)|\(candidate\)|\(company\)|\(interview\)|\(ci\)|\(terraform\)|\(db\)|\(lambdas\)|\(script\)|\(video\)): .+"
          EXCEPTIONS="^(Merge to Production|Merge to Staging|docs:.*|docs\(.*\)|fix:.*|chore|chore\(.*\))$"

          if [[ $PR_TITLE =~ $EXCEPTIONS ]]; then
              echo "PR title is an allowed exception."
          elif ! [[ $PR_TITLE =~ $PATTERN ]]; then
              echo "PR title does not match the required format"
              exit 1
          fi

  check-build-web:
    name: Check Build (Web)
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Web Files Changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            package:
              - 'web/**'

      - uses: actions/setup-node@v4
        if: steps.changes.outputs.package == 'true'
        with:
          cache: npm
          node-version: 20

      - name: Install dependencies
        if: steps.changes.outputs.package == 'true'
        run: npm install
        working-directory: web

      - name: Build
        if: steps.changes.outputs.package == 'true'
        id: build
        run: npm run build || echo "status=failed" >> $GITHUB_OUTPUT
        working-directory: web

      - name: Check build
        if: steps.changes.outputs.package == 'true'
        run: |
          if [ "${{ steps.build.outputs.status }}" = "failed" ]; then
            echo "The build failed. Please fix the errors and try again."
            exit 1
          else
            echo "The build was successful; proceeding."
          fi
