name: PR Pipeline

on:
  pull_request:

jobs:
  validate:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Compare PR title with Regex
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PATTERN="^(feat|fix|chore)(\(web\)|\(authentication\)|\(authorizer\)|\(checklist\)|\(company\)|\(position\)|\(ci\)|\(terraform\)|\(db\)): .+"
          EXCEPTIONS=("Merge to Production" "Merge to Staging" "chore")

          if [[ " ${EXCEPTIONS[@]} " =~ " $PR_TITLE " ]]; then
              echo "PR title is an allowed exception."
          elif ! [[ $PR_TITLE =~ $PATTERN ]]; then
              echo "PR title does not match the required format 'type(scope): description' or 'type: description'"
              exit 1
          fi
