name: Pull Request Pipeline (Production)

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - reopened
      - synchronize

jobs:
    analyze-commits:
      name: Analyze
      uses: ./.github/workflows/job-analyze-commits.yml
      with:
        pull_request_number: ${{ github.event.pull_request.number }}
      secrets: inherit

    create-release-web:
      needs: analyze-commits
      if: ${{ needs.analyze-commits.outputs.should_prepare_web_release == 'true' }}
      name: Create Release (web)
      uses: ./.github/workflows/job-create-release.yml
      with:
        component: web
        environment: production

    create-release-server:
      needs: analyze-commits
      if: ${{ needs.analyze-commits.outputs.should_prepare_server_release == 'true' }}
      name: Create Release (server)
      uses: ./.github/workflows/job-create-release.yml
      with:
        component: server
        environment: production
