name: PR Pipeline (Production)

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  check-infrastructure-changes:
    name: Check Infrastructure Changes
    runs-on: ubuntu-latest
    outputs:
      infra-changed: ${{ steps.check.outputs.infra-changed }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Infrastructure Files Changed
        uses: dorny/paths-filter@v3
        id: changes-infrastructure
        with:
          filters: |
            package:
              - 'terraform/**'

      - name: Set output
        id: check
        run: echo "infra-changed=${{ steps.changes-infrastructure.outputs.package }}" >> $GITHUB_OUTPUT

  plan-infrastructure-shared:
    name: Plan
    needs: [check-infrastructure-changes]
    if: needs.check-infrastructure-changes.outputs.infra-changed == 'true'
    uses: ./.github/workflows/job-plan-infrastructure.yml
    with:
      environment: production
      environment-label: Production
      component: shared
      label: Shared Infrastructure
    secrets: inherit
