name: Pull Request Pipeline (Production)

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  cleanup-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Remove previous artifacts
        uses: actions/github-script@v5
        with:
          script: |
            const repoOwner = context.repo.owner
            const repoName = context.repo.repo
            const runId = context.runId
            const artifactResponse = await github.rest.actions.listWorkflowRunArtifacts({
              owner: repoOwner,
              repo: repoName,
              run_id: runId
            });
            const artifacts = artifactResponse.data.artifacts;
            console.log(`Found ${artifacts.length} artifacts.`);
            for (const artifact of artifacts) {
              await github.rest.actions.deleteArtifact({
                owner: repoOwner,
                repo: repoName,
                artifact_id: artifact.id
              });
              console.log(`Deleted artifact: ${artifact.name} (${artifact.id})`);
            }

  analyze-commits:
    name: Analyze
    uses: ./.github/workflows/job-analyze-commits.yml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
    secrets: inherit
