name: Push Pipeline (Production)

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    name: Clean up deployment history
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 🗑 Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          environment: production
          token: ${{ secrets.GH_TOKEN }}
          onlyRemoveDeployments: true

  deploy-to-s3:
    name: Deployment
    needs: [cleanup]
    if: needs.check-for-web-folder-changes.outputs.package_changed == 'true'
    uses: ./.github/workflows/job-deploy-to-s3.yml
    with:
      environment: production
