name: Production Web

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'

jobs:
  cleanup:
    name: Clean up Deployment History
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 🗑 Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          environment: production
          token: ${{ secrets.GH_TOKEN }}
          onlyRemoveDeployments: true

  deploy-to-s3:
    name: Deploy to S3
    needs: cleanup
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ENVIRONMENT: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set execute permissions for deploy script
        run: chmod +x scripts/deploy_to_s3.sh
      - name: Deploy to S3
        shell: bash
        run: |
          cd scripts && ./deploy_to_s3.sh --bucket-name ${{ secrets.WEBSITE_BUCKET_NAME }} --environment ${{ env.ENVIRONMENT }}
