name: Push Pipeline (Production)

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    name: Clean Deployment History
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 🗑 Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          environment: production
          token: ${{ secrets.GH_TOKEN }}
          onlyRemoveDeployments: true

  deploy-website:
    name: Deployment
    needs: [cleanup]
    uses: ./.github/workflows/job-deploy-website.yml
    with:
      environment: production
